name: rtmp_streaming_example
description: Demonstrates how to use the rtmp_streaming plugin.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  rtmp_streaming:
    path: ../

  path_provider: ^2.1.5
  cupertino_icons: ^1.0.8
  wakelock_plus: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
