name: rtmp_streaming
description: An extension of the Flutter camera plugin that enables live video streaming over RTMP on Android and iOS devices.
version: 0.0.5
homepage: https://github.com/whevether/flutter_rtmp_broadcaster

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  path_provider: ^2.1.5

  flutter_test:
    sdk: flutter

  flutter_driver:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.app.rtmp_publisher
        pluginClass: RtmppublisherPlugin
      ios:
        pluginClass: RtmppublisherPlugin
