name: Publish

on:
  release:
    types: [published]
    
jobs:
  test:
    runs-on: ubuntu-latest
    name: Publish to pub.dev
    steps:
      - uses: actions/checkout@v1
      - run: ./scripts/setup-env.sh
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - uses: mikefarah/yq@3.3.0
        with: 
          cmd: yq w -i pubspec.yaml 'version' "${GITHUB_REF#refs/tags/}"
      - name: Cache Flutter dependencies
        uses: actions/cache@v1
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.FLUTTER_VERSION }}
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
      - run: dart --version
      - run: flutter --version
      - run: flutter pub get
      - run: flutter test
      - run: mkdir -p .pub-cache
      - name: Publish
        uses: sakebook/actions-flutter-pub-publisher@v1.3.0
        with:
          credential: ${{ secrets.CREDENTIAL_JSON }}
          flutter_package: true
          skip_test: true
          dry_run: false
      - name: Add-and-commit
        uses: EndBug/add-and-commit@v4
        with:
          author_name: David Bennett
          author_email: pinkfishfrog@gmail.com
          message: "Update version to {{ GITHUB_REF }}"
          add: "*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
